schedule = "https://lolesports.com/schedule?leagues=msi,lec,lck,lcs,lpl,worlds,all-star"
lpl = "https://lolesports.com/live/lpl/lpl"
lck = "https://lolesports.com/live/lck/lck"
lec = "https://lolesports.com/live/lec/lec"
lcs = "https://lolesports.com/live/lec/lcs"
msi = "https://lolesports.com/live/msi/riotgames"
worlds = "https://lolesports.com/live/worlds/riotgames"
